name: Package test

on:
  pull_request:
  issue_comment:
    types: [created]  # run when comment added with "ğŸ“¦"

jobs:
  # run package test on pull request event (but not on drafts)
  package:
    if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Diff and review changed/added packages
        uses: kaste/st_package_reviewer/gh_action@463ce04e289b5b4158230802c5c867d8719daefa
        with:
          pr: ${{ github.event.pull_request.html_url }}
          file: repository.json

  # run package test on demand via comment on the pr
  package_comment:
    if: ${{ github.event_name == 'issue_comment' && github.event.issue.pull_request != null && contains(github.event.comment.body, 'ğŸ“¦') }}
    runs-on: ubuntu-latest
    steps:
      - name: Diff and review changed/added packages
        uses: kaste/st_package_reviewer/gh_action@463ce04e289b5b4158230802c5c867d8719daefa
        with:
          pr: ${{ github.event.issue.pull_request.html_url }}
          file: repository.json
